services:
  mysql:
    image: mysql:8.0
    env_file:
      - .mysql-env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  all-in:
    image: cornellappdev/all-in:${IMAGE_TAG}
    ports:
      - "8080:8080"
    env_file:
      - .all-in-env
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql-data:
